---
version: 0
name: ExampleServer
bmcConfig:
  host: '10.93.130.125'
  user: root
  password: 0penBmc
  redfishPort: 4443
  sshPort: 22
numHosts: 1
hosts:
  - host1:
    ip: hostIP1
    user: hostUser1
    password: hostPassword1
  - host2:
    ip: hostIP2
    user: hostUser2
    password: hostPassword2
testdata:
  system:
    guid: guid-string
  cpu:
    - manufacturer: ""
      model: ""
      architecture: ""
      instructionSet: ""
      type: ""
  voltage:
    - TestString 1
    - TestString 2
  temperatures:
    - Test Temp 1
    - Test Temp 2
  fans:
    - Test Fans 1
    - Test Fans 2
  dimms:
    count: 0
    partNo: 0123
    vendor: TestDimmmVendor
    capacity: 1336
  fru:
    Board:
      productManufacturer: TestVal
      productName: 'testName'
      productSerial: 'testSerial'
      boardManufacturer: testManufacturer
