bugfix:
  - head-branch:
      - '^fix'
dependencies:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - 'go.mod'
              - 'go.sum'
documentation:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - '*.md'
              - 'docs/**'
      - head-branch:
          - '^docs'
github_actions:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - '.github/workflows/**'
      - head-branch:
          - '^ci'
go:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - '*.go'
              - '.golangci.yml'
              - '.goreleaser.yaml'
              - 'go.mod'
              - 'go.sum'
testing:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - '.checkov.yml'
              - '.commitlint.config.mjs'
              - '.cspell.json'
              - '.dagger-ci/daggerci/tests/**'
              - '.hadolint.yaml'
              - '.markdown-link-check.json'
              - '.markdownlint.json'
              - '.mega-linter.yml'
              - '.trivy.yaml'
              - '*_test.go'
      - head-branch:
          - '^test'
feature:
  - any:
      - head-branch:
          - '^feat'
          - '^feature'
