---
APPLY_FIXES: all
DISABLE:
  - COPYPASTE
DISABLE_LINTERS:
  - CSS_STYLELINT
  - GO_GOLANGCI_LINT
  - GO_REVIVE
  - REPOSITORY_KICS
  - SPELL_LYCHEE
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false

# Spelling
SPELL_CSPELL_ANALYZE_FILE_NAMES: false
SPELL_CSPELL_DISABLE_ERRORS: true

# yaml v8r
YAML_V8R_DISABLE_ERRORS: true
YAML_V8R_FILTER_REGEX_EXCLUDE: (contrib/)

# checkov
REPOSITORY_CHECKOV_FILTER_REGEX_EXCLUDE: (contrib/)

# Zizmor
ACTION_ZIZMOR_UNSECURED_ENV_VARIABLES:
  - GITHUB_TOKEN
ACTION_ZIZMOR_DISABLE_ERRORS: true
