---
name: build
on:
  pull_request:
  merge_group:
  push:
    branches: ['main']
    tags: ['v*']

permissions:
  contents: read

jobs:
  build-cross:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        shell: bash
        run: sudo apt-get install -y golang make
      - name: build
        shell: bash
        run: make cross

  build-native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        shell: bash
        run: sudo apt-get install -y golang make
      - name: build
        shell: bash
        run: make native
