---
name: build
on:
  pull_request:
  merge_group:
  push:
    branches: ['main']
    tags: ['v*']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: install taskfile
        uses: arduino/setup-task@v2
      - name: build
        run: |
          task build
